### PR TITLE
use bufferedamountlow if available

### PR DESCRIPTION
**Pull request by fippo**
this is safer than the current polling mechanism

### CODE REVIEW

**Comment by fippo** [comment]
tested with chrome 46 and jingle-interop-demos. Somewhat odd that the first strategy did not work but the event is defined as "changes". Which is odd but...

**Comment by fippo** [comment]
@tgabi333 @xdumaine can you take a look? I get some odd behaviour with bufferedAmountLow not firing always so adding a small polling thing as a fallback. This is still better than the current stuff and fixes https://github.com/andyet/SimpleWebRTC/issues/519 afaict

**Comment by fippo** [comment]
turned out that bufferedamountlow fires if you write it all lowercase :-/

**Comment by tgabi333** [comment]
:+1: thanks

**Pull request merged**
